version: '3.7'
services:
  app:
    image: 'alatoo-news'
    build: ./
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - postgresql

  postgresql:
    image: postgres:alpine
    container_name: alatoonewsdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=alatoo#news#4
      - POSTGRES_DB=news